
//package functional;
import java.util.Arrays;
import java.util.List;
import java.util.stream.*;
import java.util.function.*;
import java.util.*;


public class Week9Exercises {
	public static void main(String[] args) {
		List<Integer> ints = Arrays.asList(5, 3, 25, 7, 63, 4, 73, 42, 72, 3, 64, 6, 0, -34, 2, -521, 32);
		List<String> strings = Arrays.asList("HELLO", "aPpLe", "WORLD", "carrot", "JAVA", "cow", "fig", "PROGRAMMING");
		List<Double> doubles = List.of(32.1, 2.76, 3.0, 1.45, 89.2);
		List<String> namesList = List.of("Mary", "Jane");
		List<Integer> ints2 = Arrays.asList(5, -3, 15, 7, 3);

		/*
		 * 1. Use a Predicate to filter a list of integers, keeping only those that are
		 * divisible by 3.
		 */

		Predicate<Integer> divBy3 = ;// YOUR CODE - function that can be applied
		
		List<Integer> integers = ints.stream().filter(divBy3).collect(Collectors.toList());
        System.out.println("Input:" + ints);
        System.out.println("output:" + integers + "\n");

		/*
		 * 2. Create a Function that takes a double and returns the whole number
		 * portion.
		 */
		Function<Double, Integer> intPart = d -> d.intValue();

        List<Integer> wholeParts = doubles.stream().map(intPart).collect(Collectors.toList());
        System.out.println("Input:" + doubles);
        System.out.println("Output: " + wholeParts + "\n");

		/* 3. Use a Consumer to print each string in a list in lowercase. */

		//Your code
		System.out.print("Output: ");
        strings.forEach(s -> System.out.print(s.toLowerCase() + " "));
        System.out.println("\n");

		/*
		 * 4. Write code that filters a list of integers to keep only those greater than
		 * 50 and divisible by 3. Combine multiple predicates and resuse your predicate
		 * from 1.
		 */
		Predicate<Integer> greaterThan50 = n -> n > 50;
        List<Integer> combined = ints.stream()
                .filter(divBy3.and(greaterThan50))
                .collect(Collectors.toList());
        System.out.println("Input:" + ints);
        System.out.println("Output(div by 3, greater than 50): " + combined + "\n");
		/*
		 * 5.  Write code to square each number in a list of integers and then calculate the
		 * sum of all squared values.
		 */

		
		//Your code
		int sumSquares = ints2.stream().map(n -> n * n).reduce(0, Integer::sum);
		System.out.println("Input:" + ints2);
		System.out.println("Output(Sum of squares): " + sumSquares);

		/*
		 *6. Write a function to add a prefix "Hello, " to a given string. Apply it to a
		 * list of names.
		 */

		Function<String, String> addHello = s -> "Hello " + s;
        List<String> prefixed = namesList.stream().map(addHello).collect(Collectors.toList());
        System.out.println("Input:" + namesList);
        System.out.println("Output: " + prefixed + "\n");

		/*
		 * 7. Write a function that converts a number to its cube.
		 * Write a function that converts a number to a string prefixed by "Result: ".
		 * Chain these functions and
		 * apply them to a list of numbers.
		 */
		
		//Your code
		Function<Integer, Integer> cube = n -> n * n * n;
        Function<Integer, String> resPrefix = n -> "Result: " + n;
        List<String> cubedRes = ints2.stream()
                .map(cube.andThen(resPrefix))
                .collect(Collectors.toList());
        System.out.println("Input:" + ints2);
        System.out.println("Output (cubed and prefixed with Result): " + cubedRes + "\n");
		/**
		 * 8. Write a Supplier to generate random integers between 1 and 100.
		 * Call the supplier 10 times and create a list of the the generated values.
		 */

		//Your code
		Supplier<Integer> randGen = () -> new Random().nextInt(100) + 1;
        List<Integer> randList = Stream.generate(randGen).limit(10).collect(Collectors.toList());
        System.out.println("List generated by Supplier: " + randList + "\n");

		/**
		 * 9.  Create a BiFunction that takes two strings
		 * and returns their concatenation with a space in between.
		 * Use it on pairs of strings.
		 * https://docs.oracle.com/javase/8/docs/api/java/util/function/BiFunction.html
		 */
		//Your code
		BiFunction<String, String, String> join = (s1, s2) -> s1 + " " + s2;
        System.out.println("Input: {Hello, Dear}");
        System.out.println("Output: " + join.apply("Hello", "Dear"));
        
        List<String> strList2 = List.of("Would", "this", "darkness", "ever", "lift?");
        String sentence = strList2.stream().reduce(join::apply).orElse("");
        System.out.println("Input: " + strList2);
        System.out.println("Output: " + sentence + "\n");

		/**
		 * 10. Write a method that takes a list of strings and a Predicate<String> as
		 * arguments.
		 * The method should return a new list containing only the strings that satisfy
		 * the predicate. Test it with:
		 * (a) Strings that start with "P",
		 * (b) Strings longer than 4 characters.
		 */
	
		//Your code


		List<String> list3 = List.of("amy", "Peter", "Pam", "Paul", "Neela", "Porter");
        System.out.println("InputList: " + list3);
        List<String> filtered = filterList(list3, s -> s.startsWith("P"));
        System.out.println("Filtered List: " + filtered);
	}
}